// Karten: g = der | die | das | pl | x (kein Artikel).
window.CARDS = [
 {"id":"grundlage","g":"die","w":"Grundlage","hint":"die Grundlage, -n","ar":"الأساس","ex":"Eine gute Lage ist die Grundlage für eine schöne Wohnung.","tr":"الموقع الكويس هو أساس الشقة الحلوة.","note":"في الورقة مكتوب «Standart»، الصح «der Standard». ومرادف أدق لـ Grundlage هو «die Basis»."},
 {"id":"hauptsache","g":"die","w":"Hauptsache","hint":"die Hauptsache","ar":"أهم حاجة / المهم","ex":"Hauptsache, die Wohnung ist ruhig.","tr":"المهم إن الشقة تكون هادية."},
 {"id":"stabil","g":"x","w":"stabil","hint":"Adjektiv","ar":"متين / ثابت","ex":"Das Regal ist sehr stabil.","tr":"الرف متين جداً."},
 {"id":"wohnsitz","g":"der","w":"Wohnsitz","hint":"der feste Wohnort / der feste Wohnsitz","ar":"محل إقامة ثابت","ex":"Er hat noch keinen festen Wohnsitz.","tr":"هو لسه معندوش محل إقامة ثابت."},
 {"id":"festewohnung","g":"die","w":"feste Wohnung","hint":"eine feste Wohnung","ar":"شقة ثابتة (مش مؤقتة)","ex":"Nach dem Studium sucht sie eine feste Wohnung.","tr":"بعد الدراسة هي بتدور على شقة ثابتة."},
 {"id":"eng","g":"x","w":"eng","hint":"Adjektiv (≠ geräumig)","ar":"ضيق","ex":"Die Küche ist sehr eng, wir haben wenig Platz.","tr":"المطبخ ضيق جداً، مفيش مكان كفاية."},
 {"id":"atmen","g":"x","w":"Man kann nicht atmen.","hint":"atmen, atmete, hat geatmet","ar":"الواحد مش قادر ياخد نفسه","ex":"Das Zimmer ist so klein, man kann kaum atmen.","tr":"الأوضة صغيرة أوي، الواحد بالعافية بياخد نفسه."},
 {"id":"atemprobleme","g":"pl","w":"Atemprobleme","hint":"die Atemprobleme (Plural)","ar":"مشاكل في التنفس","ex":"Wegen der feuchten Wände hat er Atemprobleme.","tr":"بسبب الحيطان اللي فيها رطوبة عنده مشاكل في التنفس."},
 {"id":"mittel","g":"das","w":"Mittel","hint":"das Mittel, -","ar":"وسيلة / طريقة","ex":"Lüften ist ein gutes Mittel gegen Schimmel.","tr":"التهوية وسيلة كويسة ضد العفن.","note":"في الورقة مكتوب «die Mittel»، ده الجمع. المفرد «das Mittel»."},
 {"id":"mitte","g":"die","w":"Mitte","hint":"die Mitte","ar":"النص / المنتصف","ex":"Der Tisch steht in der Mitte des Zimmers.","tr":"الترابيزة في نص الأوضة."},
 {"id":"stadtmitte","g":"die","w":"Stadtmitte","hint":"die Stadtmitte = das Stadtzentrum","ar":"وسط البلد","ex":"Wir wohnen direkt in der Stadtmitte.","tr":"إحنا ساكنين في وسط البلد على طول."},
 {"id":"reisende","g":"pl","w":"Reisenden","hint":"die Reisenden (Plural) / ein Reisender","ar":"المسافرين","ex":"Die Reisenden warten am Bahnhof auf den Zug.","tr":"المسافرين مستنيين القطر في المحطة."},
 {"id":"campus","g":"der","w":"Campus","hint":"der Campus","ar":"الحرم الجامعي","ex":"Das Studentenwohnheim liegt direkt auf dem Campus.","tr":"السكن الجامعي موجود جوه الحرم الجامعي.","note":"الـ Campus معناه أرض الجامعة كلها (مباني ومكتبة وسكن)، مش WG. الورقة مختصرة المعنى أوي."},
 {"id":"kuestenstadt","g":"die","w":"Küstenstadt","hint":"die Küstenstadt, -städte","ar":"مدينة ساحلية","ex":"Alexandria ist eine Küstenstadt.","tr":"إسكندرية مدينة ساحلية.","note":"«Küste» غالباً معناها ساحل البحر. مدينة على بحيرة بيقولوا عليها أكتر «eine Stadt am See»."},
 {"id":"keks","g":"x","w":"jemandem auf den Keks gehen","hint":"umgangssprachlich (geht, ging, ist gegangen)","ar":"يعصّب حد / يضايقه","ex":"Der Lärm von den Nachbarn geht mir auf den Keks.","tr":"دوشة الجيران بتعصبني.","note":"الشكل الكامل للتعبير: «jemandem auf den Keks gehen»، ومش بيتقال «auf Keks»."},
 {"id":"wurst","g":"x","w":"Das ist mir Wurst.","hint":"umgangssprachlich = Das ist mir egal.","ar":"مش فارقة معايا","ex":"Ob wir Pizza oder Pasta essen, ist mir Wurst.","tr":"ناكل بيتزا ولا مكرونة، مش فارقة معايا."},
 {"id":"fernverkehr","g":"der","w":"Fernverkehr","hint":"der Fernverkehr","ar":"المواصلات بين المدن (مسافات طويلة)","ex":"Der ICE fährt im Fernverkehr.","tr":"قطر الـ ICE بيمشي بين المدن."},
 {"id":"nahverkehr","g":"der","w":"Nahverkehr","hint":"der (öffentliche) Nahverkehr","ar":"المواصلات جوه المدينة","ex":"Mit dem Nahverkehr kommt man schnell in die Stadtmitte.","tr":"بالمواصلات الداخلية توصلي وسط البلد بسرعة."},
 {"id":"flaeche","g":"die","w":"Fläche","hint":"die Fläche, -n","ar":"مساحة","ex":"Die Wohnung hat eine Fläche von 70 Quadratmetern.","tr":"مساحة الشقة 70 متر مربع.","note":"Fläche معناها مساحة أو سطح بشكل عام، مش لازم تكون ملكك."},
 {"id":"grundstueck","g":"das","w":"Grundstück","hint":"das Grundstück, -e","ar":"قطعة أرض","ex":"Sie haben ein Grundstück gekauft und bauen ein Haus.","tr":"اشتروا حتة أرض وبيبنوا بيت."},
 {"id":"klassisch","g":"x","w":"klassisch","hint":"Adjektiv","ar":"كلاسيكي","ex":"Das Wohnzimmer ist klassisch eingerichtet.","tr":"أوضة المعيشة متفرشة ستايل كلاسيكي."},
 {"id":"hinweis","g":"der","w":"Hinweis","hint":"der Hinweis, -e ≈ der Tipp, das Zeichen, der Denkanstoß","ar":"ملاحظة / تلميح / إشارة","ex":"Danke für den Hinweis!","tr":"شكراً على الملاحظة!"},
 {"id":"begrenzt","g":"x","w":"begrenzt","hint":"Adjektiv","ar":"محدود","ex":"Die Parkplätze vor dem Haus sind begrenzt.","tr":"أماكن الركنة قدام البيت محدودة."},
 {"id":"wg","g":"die","w":"WG","hint":"die WG = die Wohngemeinschaft, -en","ar":"سكن مشترك (ناس بيقسموا شقة وإيجار)","ex":"In unserer WG wohnen drei Studenten.","tr":"في السكن المشترك بتاعنا ساكنين تلات طلبة."},
 {"id":"studentenwohnung","g":"die","w":"Studentenwohnung","hint":"die Studentenwohnung, -en","ar":"شقة طلبة","ex":"Die Studentenwohnung ist klein, aber günstig.","tr":"شقة الطلبة صغيرة بس رخيصة."},
 {"id":"privatsphaere","g":"die","w":"Privatsphäre","hint":"die Privatsphäre","ar":"الخصوصية","ex":"In einer WG hat man weniger Privatsphäre.","tr":"في السكن المشترك الخصوصية بتبقى أقل."},
 {"id":"fliese","g":"die","w":"Fliese","hint":"die Fliese, -n (auch: die Fliesenplatte)","ar":"بلاطة / سيراميك","ex":"Im Bad sind die Fliesen weiß.","tr":"السيراميك في الحمام أبيض."},
 {"id":"bestehen","g":"x","w":"bestehen aus","hint":"bestehen aus + Dativ (besteht, bestand, hat bestanden)","ar":"يتكوّن من","ex":"Die Wohnung besteht aus drei Zimmern, einer Küche und einem Bad.","tr":"الشقة بتتكون من تلات أوض ومطبخ وحمام."},
 {"id":"qm","g":"der","w":"Quadratmeter","hint":"der Quadratmeter, - (m²)","ar":"متر مربع","ex":"Die Miete kostet 12 Euro pro Quadratmeter.","tr":"الإيجار 12 يورو للمتر المربع."},
 {"id":"laenge","g":"die","w":"Länge","hint":"die Länge, -n","ar":"الطول","ex":"Das Zimmer hat eine Länge von fünf Metern.","tr":"طول الأوضة خمسة متر.","note":"في الورقة مكتوب «lenght»، الإنجليزي الصح «length»."},
 {"id":"breite","g":"die","w":"Breite","hint":"die Breite, -n","ar":"العرض","ex":"Das Bett hat eine Breite von 1,60 Metern.","tr":"عرض السرير متر وستين."},
 {"id":"fast","g":"x","w":"fast","hint":"≈ beinahe","ar":"تقريباً (قرب يخلص)","ex":"Ich bin mit dem Aufräumen fast fertig.","tr":"أنا قربت أخلص الترويق.","note":"فيه فرق صغير: «fast» = قرب/كاد. «ungefähr» و«ca.» = حوالي (رقم مش مظبوط). «gegen» = حوالي مع الوقت: «gegen 18 Uhr»."},
 {"id":"insgesamt","g":"x","w":"insgesamt","hint":"Adverb","ar":"في المجموع / إجمالاً","ex":"Insgesamt zahlen wir 900 Euro Miete.","tr":"إحنا بندفع 900 يورو إيجار في المجموع."},
 {"id":"rechnung","g":"die","w":"Rechnung","hint":"die Rechnung, -en","ar":"فاتورة / الحساب","ex":"Die Stromrechnung kommt jeden Monat.","tr":"فاتورة الكهربا بتيجي كل شهر."},
 {"id":"gesamtpreis","g":"der","w":"Gesamtpreis","hint":"der Gesamtpreis, -e","ar":"السعر الإجمالي","ex":"Der Gesamtpreis für die Möbel ist 1.200 Euro.","tr":"السعر الإجمالي للعفش 1200 يورو."},
 {"id":"menge","g":"die","w":"Menge","hint":"die Menge, -n","ar":"كمية","ex":"Für die Wände brauchen wir eine große Menge Farbe.","tr":"محتاجين كمية كبيرة من الدهان للحيطان."},
 {"id":"huhn","g":"das","w":"Huhn","hint":"das Huhn, Hühner","ar":"فرخة (الحيوان)","ex":"Auf dem Bauernhof gibt es viele Hühner.","tr":"في المزرعة فيه فراخ كتير."},
 {"id":"haehnchen","g":"das","w":"Hähnchen","hint":"das Hähnchen, -","ar":"فراخ (كأكل)","ex":"Heute gibt es Hähnchen mit Reis.","tr":"النهارده فيه فراخ برز.","note":"Hähnchen غالباً الفرخة كأكل (مشوية، مقلية، في السوبرماركت)، مش لازم تكون مطبوخة زي ما الورقة قالت."},
 {"id":"kamin","g":"der","w":"Kamin","hint":"der Kamin, -e","ar":"مدفأة حطب (في الحيطة)","ex":"Im Winter sitzen wir gern am Kamin.","tr":"في الشتا بنحب نقعد جنب المدفأة."},
 {"id":"dienstleistung","g":"die","w":"Dienstleistung","hint":"die Dienstleistung, -en","ar":"خدمة","ex":"Die Reinigung ist eine extra Dienstleistung.","tr":"التنضيف خدمة إضافية."},
 {"id":"langfristig","g":"x","w":"langfristig","hint":"Adjektiv / Adverb","ar":"على المدى الطويل","ex":"Wir suchen langfristig eine größere Wohnung.","tr":"على المدى الطويل بندور على شقة أكبر."},
 {"id":"kurzfristig","g":"x","w":"kurzfristig","hint":"Adjektiv / Adverb","ar":"لفترة قصيرة / على آخر لحظة","ex":"Ich muss den Termin leider kurzfristig absagen.","tr":"للأسف لازم ألغي الميعاد على آخر لحظة."},
 {"id":"soviel","g":"x","w":"so viel","hint":"≠ zu viel","ar":"كتير كده / بالشكل ده","ex":"Warum kostet die Wohnung so viel?","tr":"ليه الشقة غالية كده؟","note":"«so viel» = كتير كده (so much). لو عايزة «كتير جداً» يبقى «sehr viel»."},
 {"id":"zuviel","g":"x","w":"zu viel","hint":"≠ zu wenig","ar":"كتير زيادة عن اللزوم","ex":"Wir zahlen zu viel Miete.","tr":"إحنا بندفع إيجار كتير زيادة."},
 {"id":"blick","g":"der","w":"Blick","hint":"der Blick, -e","ar":"نظرة / منظر","ex":"Aus der Küche hat man einen Blick auf den Park.","tr":"من المطبخ تقدري تشوفي الجنينة."},
 {"id":"ausblick","g":"der","w":"Ausblick","hint":"der Ausblick, -e","ar":"منظر (من مكان عالي أو من الشباك)","ex":"Vom Balkon haben wir einen tollen Ausblick auf die Berge.","tr":"من البلكونة عندنا منظر تحفة على الجبال."},
 {"id":"einblick","g":"der","w":"Einblick","hint":"der Einblick, -e","ar":"فكرة من جوه / نظرة عن قرب","ex":"Die Besichtigung gibt einen guten Einblick in die Wohnung.","tr":"المعاينة بتديكي فكرة كويسة عن الشقة من جوه."},
 {"id":"einraeumen","g":"x","w":"einräumen","hint":"räumt ein, räumte ein, hat eingeräumt","ar":"يحط الحاجة في مكانها (دولاب/أوضة)","ex":"Ich räume das Geschirr in den Schrank ein.","tr":"بحط المواعين في الدولاب."},
 {"id":"ausraeumen","g":"x","w":"ausräumen","hint":"räumt aus, räumte aus, hat ausgeräumt","ar":"يفضّي","ex":"Vor dem Umzug müssen wir die Schränke ausräumen.","tr":"قبل النقل لازم نفضي الدواليب."},
 {"id":"umraeumen","g":"x","w":"umräumen","hint":"räumt um, räumte um, hat umgeräumt","ar":"يغيّر ترتيب الأوضة","ex":"Am Wochenende haben wir das Wohnzimmer umgeräumt.","tr":"في الويك إند غيرنا ترتيب أوضة المعيشة."},
 {"id":"aufraeumen","g":"x","w":"aufräumen","hint":"räumt auf, räumte auf, hat aufgeräumt","ar":"يروّق / يرتّب","ex":"Räum bitte dein Zimmer auf!","tr":"روّق أوضتك لو سمحت!"},
 {"id":"geraeumig","g":"x","w":"geräumig","hint":"Adjektiv (≠ eng)","ar":"واسع","ex":"Die Wohnung ist hell und geräumig.","tr":"الشقة منورة وواسعة."},
 {"id":"streichen","g":"x","w":"streichen","hint":"streicht, strich, hat gestrichen","ar":"يدهن (حيطة / بيت)","ex":"Wir haben die Wände weiß gestrichen.","tr":"دهنّا الحيطان أبيض."},
 {"id":"aber","g":"x","w":"aber","hint":"Konnektor (Position 0)","ar":"لكن / بس","ex":"Die Wohnung ist klein, aber sehr gemütlich.","tr":"الشقة صغيرة بس مريحة جداً.","note":"«aber» مش بياخد مكان في الجملة (Position 0)، فالفعل بيفضل في المكان التاني بعده: «aber ich komme später»."}
];
